version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file:
      - ./be/.env
    ports:
      - 3306:3306
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
